receivers:
  # 1. Receivers the OTLP Metrics pushed from The FastAPI application
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # 2. Automatically collect underlying Metric System (RAM, CPU)
  host_metrics:
    collection_interval: 2s
    scrapers:
      cpu:
      memory:

processors:
  # Batches the metric data befor exportinf to optimaze the network usage
  batch:
    #send_batch_max_size: 1000
    timeout: 5s

exporters:
  # Print the detailed metric outputs to sdtout
  debug:
    verbosity: detailed
  
  # Direct HTTP OTLP exports to Service-A endpoints
  otlp_http/service_a:
    endpoint: "http://service-a:5000"
    #metrics_endpoint: "http://localhost:5000/v1/metrics"
    # logs_endpoint: "http://localhost:5000/v1/logs"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, host_metrics]
      processors: [batch]
      exporters: [debug, otlp_http/service_a]