receivers:
  # 1. Receivers the OTLP Metrics pushed from The FastAPI application
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # 2. Automatically collect underlying Metric System (RAM, CPU)
  hostmetrics:
    collection_interval: 2s
    scrapers:
      cpu:
      memory:

processors:
  # Batches the metric data befor exportinf to optimaze the network usage
  batch:
    send_batch_max_size: 1000
    timeout: 5s

exporters:
  # Print the detailed metric outputs to sdtout
  debug:
    verbosity: detailed
  
  # Direct HTTP OTLP exports to Service-A endpoints
  otlphttp/service_a:
    endpoint: hhtp://localhost:5000
    metrics_endpoint: /v1/logs
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [debug, otlphttp/service_a]