# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"t\n\rMetricPayload\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x11\n\tcpu_usage\x18\x02 \x01(\x01\x12\x11\n\tram_usage\x18\x03 \x01(\x01\x12\x14\n\x0cmemory_usage\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"Y\n\nLogPayload\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x11\n\tlog_level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"z\n\x0f\x41nomalyResponse\x12\x12\n\nis_anomaly\x18\x01 \x01(\x08\x12\x15\n\ranomaly_score\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\'\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x17.telemetry.StatutAction*/\n\x0cStatutAction\x12\x08\n\x04PASS\x10\x00\x12\x15\n\x11RESTART_CONTAINER\x10\x01\x32\xa1\x01\n\x0f\x41nomalyDetector\x12I\n\rStreamMetrics\x12\x18.telemetry.MetricPayload\x1a\x1a.telemetry.AnomalyResponse(\x01\x30\x01\x12\x43\n\nAnalyzeLog\x12\x15.telemetry.LogPayload\x1a\x1a.telemetry.AnomalyResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUTACTION']._serialized_start=363
  _globals['_STATUTACTION']._serialized_end=410
  _globals['_METRICPAYLOAD']._serialized_start=30
  _globals['_METRICPAYLOAD']._serialized_end=146
  _globals['_LOGPAYLOAD']._serialized_start=148
  _globals['_LOGPAYLOAD']._serialized_end=237
  _globals['_ANOMALYRESPONSE']._serialized_start=239
  _globals['_ANOMALYRESPONSE']._serialized_end=361
  _globals['_ANOMALYDETECTOR']._serialized_start=413
  _globals['_ANOMALYDETECTOR']._serialized_end=574
# @@protoc_insertion_point(module_scope)
