# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as protobuf_dot_telemetry__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protobuf/telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnomalyDetectorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMetrics = channel.stream_stream(
                '/telemetry.AnomalyDetector/StreamMetrics',
                request_serializer=protobuf_dot_telemetry__pb2.MetricPayload.SerializeToString,
                response_deserializer=protobuf_dot_telemetry__pb2.AnomalyResponse.FromString,
                _registered_method=True)
        self.AnalyzeLog = channel.stream_stream(
                '/telemetry.AnomalyDetector/AnalyzeLog',
                request_serializer=protobuf_dot_telemetry__pb2.LogPayload.SerializeToString,
                response_deserializer=protobuf_dot_telemetry__pb2.MetricPayload.FromString,
                _registered_method=True)


class AnomalyDetectorServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamMetrics(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLog(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=protobuf_dot_telemetry__pb2.MetricPayload.FromString,
                    response_serializer=protobuf_dot_telemetry__pb2.AnomalyResponse.SerializeToString,
            ),
            'AnalyzeLog': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeLog,
                    request_deserializer=protobuf_dot_telemetry__pb2.LogPayload.FromString,
                    response_serializer=protobuf_dot_telemetry__pb2.MetricPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.AnomalyDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.AnomalyDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetector:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/telemetry.AnomalyDetector/StreamMetrics',
            protobuf_dot_telemetry__pb2.MetricPayload.SerializeToString,
            protobuf_dot_telemetry__pb2.AnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLog(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/telemetry.AnomalyDetector/AnalyzeLog',
            protobuf_dot_telemetry__pb2.LogPayload.SerializeToString,
            protobuf_dot_telemetry__pb2.MetricPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
